/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    appName: "EmergX",
    sosPanic: "⚡ SOS PANIC",
    activeEmergency: "ACTIVE EMERGENCY",
    viewMode: "VIEW MODE:",
    resident: "🏠 Resident",
    security: "🛡️ Security Guard",
    volunteer: "🤝 Volunteer",
    admin: "📊 Admin Portal",
    dispatchCenter: "EMERGENCY DISPATCH CENTER",
    instantBroadcast: "Instant Community Emergency Broadcast",
    panicDesc: "Pressing the panic button alerts active housing security guards, nearby verified volunteers, and emergency contact list in priority order.",
    pressPanic: "PRESS PANIC",
    tapCategory: "OR TAP SPECIFIC EMERGENCY CATEGORY:",
    medicalEmergency: "Medical Emergency",
    fireHazard: "Fire Hazard",
    securityThreat: "Security Threat",
    naturalDisaster: "Natural Disaster",
    generalSOS: "General SOS",
    activeAlertsCount: "Active Community SOS Alerts",
    emergencyContactsList: "Emergency Contacts List",
    onDutySecurity: "On Duty Security Gate",
    volunteerResponders: "Neighborhood Volunteers",
    activeFeedTitle: "Active Emergency Feed & Incident Logs",
    noActiveAlerts: "No Active Emergency Alerts",
    safeCommunityMsg: "Your housing community is currently safe. Responders are on standby.",
    liveCountdownTitle: "LIVE ESCALATION COUNTDOWN TIMER",
    secsToNextTier: "Secs to Next Tier",
    acceptedByResponder: "ACCEPTED",
    tier1: "Security Personnel",
    tier2: "Volunteer Responders",
    tier3: "Primary Contact",
    tier4: "Secondary Contact",
    home: "Home Dashboard",
    contacts: "Emergency Contacts",
    history: "Incident Audit Log",
    alerts: "Alerts & Messages",
    profile: "User Profile",
    signOut: "Sign Out",
    overviewStats: "Overview Stats",
    manageSocieties: "Manage Societies",
    manageResidents: "Manage Residents & Roles",
    systemBroadcasts: "System Broadcasts",
    guardsCommandCenter: "Guards Command Center",
    volunteerPortalNav: "Volunteer Portal",
    pastIncidents: "Past Incidents",
    communityBroadcasts: "Community Broadcasts",
    mainMenu: "MAIN MENU",
    volunteerNetwork: "NEIGHBORHOOD VOLUNTEER NETWORK",
    volunteerSubtitle: "Provide immediate first-aid, CPR, or neighbor assistance until professional first responders arrive.",
    volunteerStatusOnCall: "🟢 VOLUNTEER ACTIVE STATUS: ON CALL",
    nearbyEmergencies: "Nearby Neighborhood Emergencies",
    iCanAssist: "🤝 I Can Assist (Respond)",
    youResponded: "✓ You responded: On the way!",
    noNearbyEmergencies: "No active neighbor emergency requests nearby.",
    adminDashboardTitle: "Admin Command & Governance Dashboard",
    adminDashboardSubtitle: "System overview, community emergency metrics, society management, and resident role assignment.",
    regSocieties: "Registered Societies",
    totResidents: "Total Resident Users",
    activeSOS: "Active Emergency SOS",
    securityOnDuty: "Security Guards On Duty",
    configSocieties: "Configure Housing Societies",
    configSocietiesDesc: "Add new residential societies, configure building blocks, and define flat layouts.",
    manageSocietiesBtn: "Manage Societies →",
    manageUserRoles: "Manage Residents & Roles",
    manageUserRolesDesc: "Approve registered accounts, assign Security Guard / Volunteer roles, and map flat numbers.",
    manageUserRolesBtn: "Manage User Roles →",
    auditLogs: "Emergency Audit Logs",
    auditLogsDesc: "View system audit reports, historical response timelines, and dispatch metrics.",
    auditLogsBtn: "View Audit Logs →",
  },
  hi: {
    appName: "EmergX",
    sosPanic: "⚡ आपातकालीन बटन (SOS)",
    activeEmergency: "सक्रिय आपातकाल",
    viewMode: "दृश्य मोड:",
    resident: "🏠 निवासी",
    security: "🛡️ सुरक्षा गार्ड",
    volunteer: "🤝 स्वयंसेवक",
    admin: "📊 व्यवस्थापक (एडमिन)",
    dispatchCenter: "आपातकालीन प्रेषण केंद्र",
    instantBroadcast: "तत्काल समुदाय आपातकालीन प्रसारण",
    panicDesc: "आपातकालीन बटन दबाने से सुरक्षा गार्ड, निकटतम सत्यापित स्वयंसेवकों और आपातकालीन संपर्कों को तुरंत सूचित किया जाता है।",
    pressPanic: "आपातकालीन बटन दबाएं",
    tapCategory: "या विशिष्ट आपातकालीन श्रेणी चुनें:",
    medicalEmergency: "चिकित्सा आपातकाल (मेडिकल)",
    fireHazard: "अग्नि संकट (फायर)",
    securityThreat: "सुरक्षा खतरा",
    naturalDisaster: "प्राकृतिक आपदा",
    generalSOS: "सामान्य आपातकाल",
    activeAlertsCount: "सक्रिय समुदाय आपातकालीन अलर्ट",
    emergencyContactsList: "आपातकालीन संपर्क सूची",
    onDutySecurity: "ड्यूटी पर सुरक्षा गेट",
    volunteerResponders: "पड़ोस के स्वयंसेवक",
    activeFeedTitle: "सक्रिय आपातकालीन स्थिति और लॉग",
    noActiveAlerts: "कोई सक्रिय आपातकालीन अलर्ट नहीं",
    safeCommunityMsg: "आपका समुदाय वर्तमान में सुरक्षित है। उत्तरदाता तैयार हैं।",
    liveCountdownTitle: "लाइव एस्केलेशन उल्टी गिनती टाइमर",
    secsToNextTier: "अगले स्तर के लिए सेकंड",
    acceptedByResponder: "उत्तरदाता द्वारा स्वीकार किया गया",
    tier1: "सुरक्षाकर्मी (सिक्योरिटी)",
    tier2: "स्वयंसेवक उत्तरदाता (वोलंटियर)",
    tier3: "प्राथमिक संपर्क (प्राइमरी)",
    tier4: "द्वितीयक संपर्क (सेकेंडरी)",
    home: "मुख्य पृष्ठ",
    contacts: "आपातकालीन संपर्क",
    history: "घटना इतिहास",
    alerts: "अलर्ट और संदेश",
    profile: "उपयोगकर्ता प्रोफ़ाइल",
    signOut: "साइन आउट करें",
    overviewStats: "अवलोकन आंकड़े",
    manageSocieties: "सोसायटी प्रबंधन",
    manageResidents: "निवासी और भूमिकाएं",
    systemBroadcasts: "सिस्टम प्रसारण",
    guardsCommandCenter: "सुरक्षा कमांड सेंटर",
    volunteerPortalNav: "स्वयंसेवक पोर्टल",
    pastIncidents: "पिछली घटनाएं",
    communityBroadcasts: "समुदाय प्रसारण",
    mainMenu: "मुख्य मेनू",
  },
  ta: {
    appName: "EmergX",
    sosPanic: "⚡ அவசர உதவி (SOS)",
    activeEmergency: "செயலில் உள்ள அவசரநிலை",
    viewMode: "பார்வை முறை:",
    resident: "🏠 குடியிருப்பாளர்",
    security: "🛡️ பாதுகாப்பு காவலர்",
    volunteer: "🤝 தன்னார்வலர்",
    admin: "📊 நிர்வாகி போர்டல்",
    dispatchCenter: "அவசரகால சேவை மையம்",
    instantBroadcast: "உடனடி சமூக அவசரகால ஒளிபரப்பு",
    panicDesc: "அவசர பொத்தானை அழுத்தினால் பாதுகாப்பு காவலர்கள், அருகில் உள்ள தன்னார்வலர்கள் மற்றும் அவசர தொடர்புகளுக்கு உடனடியாக செய்தி அனுப்பப்படும்.",
    pressPanic: "அழுத்தவும் (PANIC)",
    tapCategory: "அல்லது குறிப்பிட்ட அவசர வகையைத் தேர்ந்தெடுக்கவும்:",
    medicalEmergency: "மருத்துவ அவசரநிலை",
    fireHazard: "தீ விபத்து ஆபத்து",
    securityThreat: "பாதுகாப்பு அச்சுறுத்தல்",
    naturalDisaster: "இயற்கை பேரழிவு",
    generalSOS: "பொது அவசரநிலை",
    activeAlertsCount: "செயலில் உள்ள சமூக SOS எச்சரிக்கைகள்",
    emergencyContactsList: "அவசர தொடர்பு பட்டியல்",
    onDutySecurity: "பணியில் உள்ள பாதுகாப்பு",
    volunteerResponders: "அருகிலுள்ள தன்னார்வலர்கள்",
    activeFeedTitle: "செயலில் உள்ள அவசரகால நிலை மற்றும் பதிவுகள்",
    noActiveAlerts: "செயலில் உள்ள அவசர எச்சரிக்கைகள் எதுவும் இல்லை",
    safeCommunityMsg: "உங்கள் சமூகம் தற்போது பாதுகாப்பாக உள்ளது. தயார் நிலையில் உள்ளது.",
    liveCountdownTitle: "நேரலை கவுண்ட்டவுன் டைமர்",
    secsToNextTier: "அடுத்த நிலைக்கு வினாடிகள்",
    acceptedByResponder: "பதிலளிப்பவரால ஏற்றுக்கொள்ளப்பட்டது",
    tier1: "பாதுகாப்பு பணியாளர்கள்",
    tier2: "தன்னார்வ பதிலளிப்பவர்கள்",
    tier3: "முதன்மை தொடர்பு",
    tier4: "இரண்டாம் நிலை தொடர்பு",
    home: "முகப்பு பக்கம்",
    contacts: "அவசர தொடர்புகள்",
    history: "நிகழ்வு வரலாறு",
    alerts: "எச்சரிக்கைகள் & செய்திகள்",
    profile: "சுயவிவரம்",
    signOut: "வெளியேறு",
    overviewStats: "மேலோட்டமான புள்ளிவிவரங்கள்",
    manageSocieties: "சங்கங்கள் நிர்வாகம்",
    manageResidents: "குடியிருப்பாளர்கள் நிர்வாகம்",
    systemBroadcasts: "கணினி ஒளிபரப்புகள்",
    guardsCommandCenter: "பாதுகாப்பு தலைமை மையம்",
    volunteerPortalNav: "தன்னார்வலர் போர்டல்",
    pastIncidents: "கடந்த நிகழ்வுகள்",
    communityBroadcasts: "சமூக ஒளிபரப்புகள்",
    mainMenu: "முதன்மை பட்டி",
  },
  te: {
    appName: "EmergX",
    sosPanic: "⚡ SOS అత్యవసరం",
    activeEmergency: "సక్రియ అత్యవసరం",
    viewMode: "వీక్షణ మోడ్:",
    resident: "🏠 నివాసి",
    security: "🛡️ సెక్యూరిటీ గార్డ్",
    volunteer: "🤝 వాలంటీర్",
    admin: "📊 అడ్మిన్ పోర్టల్",
    dispatchCenter: "అత్యవసర డిస్పాచ్ సెంటర్",
    instantBroadcast: "తక్షణ అత్యవసర ప్రసారం",
    panicDesc: "బటన్ నొక్కడం ద్వారా రక్షణ గార్డులు మరియు సంబంధిత వ్యక్తులకు సమాచారం వెళ్తుంది.",
    pressPanic: "అత్యవసర బటన్ నొక్కండి",
    tapCategory: "లేదా వర్గాన్ని ఎంచుకోండి:",
    medicalEmergency: "వైద్య అత్యవసరం",
    fireHazard: "అగ్ని ప్రమాదం",
    securityThreat: "రక్షణ ముప్పు",
    naturalDisaster: "ప్రకృతి విపత్తు",
    generalSOS: "సాధారణ SOS",
    activeAlertsCount: "సక్రియ హెచ్చరికలు",
    emergencyContactsList: "అత్యవసర పరిచయాల జాబితా",
    onDutySecurity: "డ్యూటీలో సెక్యూరిటీ",
    volunteerResponders: "పొరుగు వాలంటీర్లు",
    activeFeedTitle: "సక్రియ హెచ్చరిక లాగ్‌లు",
    noActiveAlerts: "సక్రియ హెచ్చరికలు లేవు",
    safeCommunityMsg: "మీ కమ్యూనిటీ సురక్షితంగా ఉంది.",
    liveCountdownTitle: "లైవ్ ఎస్కలేషన్ కౌంట్‌డౌన్",
    secsToNextTier: "తదుపరి స్థాయికి సెకన్లు",
    acceptedByResponder: "అంగీకరించబడింది",
    tier1: "సెక్యూరిటీ సిబ్బంది",
    tier2: "వాలంటీర్లు",
    tier3: "ప్రాథమిక పరిచయం",
    tier4: "ద్వితీయ పరిచయం",
    home: "హోమ్ డాష్‌బోర్డ్",
    contacts: "అత్యవసర పరిచయాలు",
    history: "సంఘటన లాగ్",
    alerts: "హెచ్చరికలు",
    profile: "ప్రొఫైల్",
    signOut: "సైన్ అవుట్",
    overviewStats: "గణాంకాలు",
    manageSocieties: "సొసైటీ నిర్వహణ",
    manageResidents: "నివాసితుల నిర్వహణ",
    systemBroadcasts: "సిస్టమ్ ప్రసారాలు",
    guardsCommandCenter: "గార్డు సెంటర్",
    volunteerPortalNav: "వాలంటీర్ పోర్టల్",
    pastIncidents: "గత సంఘటనలు",
    communityBroadcasts: "కమ్యూనిటీ ప్రసారాలు",
    mainMenu: "ముఖ్యమైన మెనూ",
  },
  bn: {
    appName: "EmergX",
    sosPanic: "⚡ SOS জরুরি",
    activeEmergency: "সক্রিয় জরুরি",
    viewMode: "ভিউ মোড:",
    resident: "🏠 বাসিন্দা",
    security: "🛡️ নিরাপত্তা কর্মী",
    volunteer: "🤝 স্বেচ্ছাসেবক",
    admin: "📊 অ্যাডমিন পোর্টাল",
    dispatchCenter: "জরুরি কেন্দ্র",
    instantBroadcast: "তাত্ক্ষণিক জরুরি সম্প্রচার",
    panicDesc: "জরুরি বোতাম চাপলে নিরাপত্তা ও প্রাথমিক যোগাযোগকারীদের সতর্ক করা হবে।",
    pressPanic: "জরুরি বোতাম চাপুন",
    tapCategory: "অথবা বিভাগ নির্বাচন করুন:",
    medicalEmergency: "চিকিৎসা জরুরি অবস্থা",
    fireHazard: "অগ্নি দুর্ঘটনা",
    securityThreat: "নিরাপত্তা ঝুঁকি",
    naturalDisaster: "প্রাকৃতিক দুর্যোগ",
    generalSOS: "সাধারণ SOS",
    activeAlertsCount: "সক্রিয় সতর্কতা",
    emergencyContactsList: "জরুরি যোগাযোগের তালিকা",
    onDutySecurity: "অন ডিউটি সিকিউরিটি",
    volunteerResponders: "স্থানীয় স্বেচ্ছাসেবক",
    activeFeedTitle: "সক্রিয় ঘটনা লগ",
    noActiveAlerts: "কোন সক্রিয় সতর্কতা নেই",
    safeCommunityMsg: "আপনার এলাকা এখন নিরাপদ।",
    liveCountdownTitle: "লাইভ কাউন্টডাউন টাইমার",
    secsToNextTier: "পরবর্তী স্তরের সেকেন্ড",
    acceptedByResponder: "গৃহীত",
    tier1: "নিরাপত্তা কর্মী",
    tier2: "স্বেচ্ছাসেবক",
    tier3: "প্রাথমিক যোগাযোগ",
    tier4: "দ্বিতীয় যোগাযোগ",
    home: "হোম ড্যাশবোর্ড",
    contacts: "জরুরি যোগাযোগ",
    history: "ঘটনা ইতিহাস",
    alerts: "বিজ্ঞপ্তি",
    profile: "প্রোফাইল",
    signOut: "সাইন আউট",
    overviewStats: "পরিসংখ্যান",
    manageSocieties: "সোসাইটি পরিচালনা",
    manageResidents: "বাসিন্দা পরিচালনা",
    systemBroadcasts: "সিস্টেম সম্প্রচার",
    guardsCommandCenter: "গার্ড সেন্টার",
    volunteerPortalNav: "স্বেচ্ছাসেবক পোর্টাল",
    pastIncidents: "অতীত ঘটনা",
    communityBroadcasts: "কমিউনিটি সম্প্রচার",
    mainMenu: "প্রধান মেনু",
  },
  kn: {
    appName: "EmergX",
    sosPanic: "⚡ SOS ತುರ್ತು",
    activeEmergency: "ಸಕ್ರಿಯ ತುರ್ತು",
    viewMode: "ವೀಕ್ಷಣೆ ಮೋಡ್:",
    resident: "🏠 ನಿವಾಸಿ",
    security: "🛡️ ಸುರಕ್ಷತಾ ಸಿಬ್ಬಂದಿ",
    volunteer: "🤝 ಸ್ವಯಂಸೇವಕ",
    admin: "📊 ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್",
    dispatchCenter: "ತುರ್ತು ಕೇಂದ್ರ",
    instantBroadcast: "ತಕ್ಷಣದ ತುರ್ತು ಪ್ರಸಾರ",
    panicDesc: "ಬಟನ್ ಒತ್ತಿದರೆ ಸುರಕ್ಷತಾ ಸಿಬ್ಬಂದಿ ಮತ್ತು ಸಂಪರ್ಕಗಳಿಗೆ ಸೂಚನೆ ರವಾನೆಯಾಗುತ್ತದೆ.",
    pressPanic: "ತುರ್ತು ಬಟನ್ ಒತ್ತಿ",
    tapCategory: "ಅಥವಾ ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ:",
    medicalEmergency: "ವೈದ್ಯಕೀಯ ತುರ್ತು",
    fireHazard: "ಅಗ್ನಿ ಅವಘಡ",
    securityThreat: "ಸುರಕ್ಷತಾ ಬೆದರಿಕೆ",
    naturalDisaster: "ನೈಸರ್ಗಿಕ ವಿಕೋಪ",
    generalSOS: "ಸಾಮಾನ್ಯ SOS",
    activeAlertsCount: "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು",
    emergencyContactsList: "ತುರ್ತು ಸಂಪರ್ಕಗಳ ಪಟ್ಟಿ",
    onDutySecurity: "ಕರ್ತವ್ಯದಲ್ಲಿರುವ ಭದ್ರತೆ",
    volunteerResponders: "ನೆರೆಹೊರೆಯ ಸ್ವಯಂಸೇವಕರು",
    activeFeedTitle: "ಸಕ್ರಿಯ ಘಟನೆಗಳ ದಾಖಲೆ",
    noActiveAlerts: "ಯಾವುದೇ ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ",
    safeCommunityMsg: "ನಿಮ್ಮ ಸಮುದಾಯ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
    liveCountdownTitle: "ಲೈವ್ ಎಸ್ಕಲೇಶನ್ ಟೈಮರ್",
    secsToNextTier: "ಮುಂದಿನ ಹಂತಕ್ಕೆ ಸೆಕೆಂಡುಗಳು",
    acceptedByResponder: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    tier1: "ಸುರಕ್ಷತಾ ಸಿಬ್ಬಂದಿ",
    tier2: "ಸ್ವಯಂಸೇವಕರು",
    tier3: "ಪ್ರಾಥಮಿಕ ಸಂಪರ್ಕ",
    tier4: "ದ್ವಿತೀಯ ಸಂಪರ್ಕ",
    home: "ಮುಖಪುಟ",
    contacts: "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
    history: "ಘಟನೆಗಳ ದಾಖಲೆ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    signOut: "ಸೈನ್ ಔಟ್",
    overviewStats: "ಅಂಕಿಅಂಶಗಳು",
    manageSocieties: "ಸೊಸೈಟಿ ನಿರ್ವಹಣೆ",
    manageResidents: "ನಿವಾಸಿಗಳ ನಿರ್ವಹಣೆ",
    systemBroadcasts: "ಸಿಸ್ಟಮ್ ಪ್ರಸಾರಗಳು",
    guardsCommandCenter: "ಗಾರ್ಡ್ ಪೋರ್ಟಲ್",
    volunteerPortalNav: "ಸ್ವಯಂಸೇವಕ ಪೋರ್ಟಲ್",
    pastIncidents: "ಹಿಂದಿನ ಘಟನೆಗಳು",
    communityBroadcasts: "ಸಮುದಾಯ ಪ್ರಸಾರಗಳು",
    mainMenu: "ಮುಖ್ಯ ಮೆನು",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem("app_lang") || "en");

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
