import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'kn';

export interface LanguageInfo {
  code: Language;
  label: string;
  nativeLabel: string;
  flag: string;
}

export const AVAILABLE_LANGUAGES: LanguageInfo[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', flag: '🇮🇳' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appTitle: "EmergX",
    appName: "EmergX",
    sosPanicButton: "SOS",
    pressPanic: "PRESS PANIC",
    instantBroadcast: "Instant Community Emergency Broadcast",
    emergencyCategoryPrompt: "OR TAP SPECIFIC EMERGENCY CATEGORY:",
    medicalEmergency: "Medical Emergency",
    fireHazard: "Fire Hazard",
    securityThreat: "Security Threat",
    naturalDisaster: "Natural Disaster",
    generalSOS: "General SOS",
    liveCountdownTitle: "LIVE ESCALATION COUNTDOWN TIMER",
    secsToNextTier: "SECS TO NEXT TIER",
    tier1: "Security Personnel",
    tier2: "Volunteer Responders",
    tier3: "Primary Contact",
    tier4: "Secondary Contact",
    tier1Short: "Security",
    tier2Short: "Volunteer",
    tier3Short: "Primary",
    tier4Short: "Secondary",
    tierLevelHeader: "Tier",
    ofFour: "of 4:",
    welcomeBack: "Welcome Back",
    emailAddress: "Email Address",
    password: "Password",
    login: "Log In",
    loggingIn: "Logging In...",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    oneTapDemo: "One-Tap Demo Accounts:",
    acceptedByResponder: "ACCEPTED BY RESPONDER",
    emergencyResolved: "EMERGENCY RESOLVED / STOPPED",
    activeEmergencyTitle: "ACTIVE EMERGENCY ALERT",
    resolveSOS: "Resolve SOS",
    cancelSOS: "Cancel SOS",
    contactsTitle: "Emergency Contacts",
    alertsTitle: "Alert Notifications",
    profileTitle: "User Profile",
    home: "Home",
    contacts: "Contacts",
    alerts: "Alerts",
    profile: "Profile",
    languageTab: "Language",
    languageTitle: "Select App Language",
    languageSubtitle: "Choose your preferred language for full app interface",
    logout: "Log Out",
    unitLocation: "Unit / Flat Location",
    activeEmergencyBanner: "1 ACTIVE EMERGENCY IN PROGRESS",
    tapToViewEscalation: "Tap to view live 4-tier escalation & tracking modal →",
    verified: "VERIFIED",
    emergencyDispatchCenter: "EMERGENCY DISPATCH CENTER",
    broadcastDesc: "Pressing the panic button opens emergency dispatch details to specify flat location & reason before broadcasting.",
    dispatchDetails: "EMERGENCY DISPATCH DETAILS",
    specifyLocationReason: "Specify location & reason before SOS broadcast",
    flatUnitLocation: "FLAT / UNIT EMERGENCY LOCATION",
    reasonForSOS: "REASON FOR EMERGENCY SOS",
    additionalDetails: "ADDITIONAL DETAILS (OPTIONAL)",
    broadcastSOSNow: "BROADCAST SOS NOW",
    fallInjury: "Fall / Injury",
    fireSmoke: "Fire / Smoke",
    intruderSecurity: "Intruder / Security",
    adminDashboard: "Admin Dashboard",
    manageSocieties: "Manage Societies",
    manageResidents: "Manage Residents",
    guardsPortal: "Guards Portal",
    volunteersPortal: "Volunteers Portal",
    availability: "Availability",
    overviewStats: "Overview Stats",
    activeIncidents: "Active Incidents",
    resolvedIncidents: "Resolved Incidents",
    totalResidents: "Total Residents",
    totalSocieties: "Total Societies",
    addSociety: "Add Society",
    addResident: "Add Resident",
    incidentHistory: "Incident Audit Log",
    personalDetails: "Personal Details",
    societyResidenceMapping: "Society Residence Mapping",
    activeRole: "Active Role",
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    save: "Save",
    edit: "Edit",
    cancel: "Cancel",
    addContact: "Add Emergency Contact",
    relationship: "Relationship",
    priority: "Priority",
    unverified: "Unverified",
    viewMode: "VIEW MODE:",
    resident: "Resident",
    security: "Security Guard",
    volunteer: "Volunteer",
    admin: "Admin",
    sosPanic: "SOS PANIC",
    activeEmergency: "ACTIVE EMERGENCY",
    activeFeedTitle: "Active Emergency Feed & Logs",
    noActiveAlerts: "No Active Emergency Alerts",
    safeCommunityMsg: "Your community is currently safe. Responders are on standby.",
    signOut: "Sign Out",
  },
  hi: {
    appTitle: "EmergX",
    appName: "EmergX",
    sosPanicButton: "SOS",
    pressPanic: "आपातकालीन बटन दबाएं",
    instantBroadcast: "तत्काल समुदाय आपातकालीन प्रसारण",
    emergencyCategoryPrompt: "या विशिष्ट आपातकालीन श्रेणी चुनें:",
    medicalEmergency: "चिकित्सा आपातकाल",
    fireHazard: "अग्नि दुर्घटना",
    securityThreat: "सुरक्षा खतरा",
    naturalDisaster: "प्राकृतिक आपदा",
    generalSOS: "सामान्य एसओएस",
    liveCountdownTitle: "लाइव एस्केलेशन उल्टी गिनती टाइमर",
    secsToNextTier: "अगले स्तर के लिए सेकंड",
    tier1: "सुरक्षाकर्मी (सिक्योरिटी)",
    tier2: "स्वयंसेवक उत्तरदाता (वोलंटियर)",
    tier3: "प्राथमिक संपर्क (प्राइमरी)",
    tier4: "द्वितीयक संपर्क (सेकेंडरी)",
    tier1Short: "सुरक्षा",
    tier2Short: "स्वयंसेवक",
    tier3Short: "प्राथमिक",
    tier4Short: "द्वितीयक",
    tierLevelHeader: "स्तर",
    ofFour: "का 4:",
    welcomeBack: "वापसी पर स्वागत है",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    login: "लॉग इन करें",
    loggingIn: "लॉग इन हो रहा है...",
    dontHaveAccount: "खाता नहीं है?",
    signUp: "साइन अप करें",
    oneTapDemo: "एक-टैप डेमो खाते:",
    acceptedByResponder: "उत्तरदाता द्वारा स्वीकार किया गया",
    emergencyResolved: "आपात स्थिति हल की गई / रोकी गई",
    activeEmergencyTitle: "सक्रिय आपातकालीन चेतावनी",
    resolveSOS: "एसओएस हल करें",
    cancelSOS: "एसओएस रद्द करें",
    contactsTitle: "आपातकालीन संपर्क",
    alertsTitle: "चेतावनी सूचनाएं",
    profileTitle: "उपयोगकर्ता प्रोफ़ाइल",
    home: "मुख्य पृष्ठ",
    contacts: "संपर्क",
    alerts: "सूचनाएं",
    profile: "प्रोफ़ाइल",
    languageTab: "भाषा",
    languageTitle: "ऐप की भाषा चुनें",
    languageSubtitle: "अपनी पसंदीदा भाषा चुनें",
    logout: "लॉग आउट",
    unitLocation: "इकाई / फ्लैट स्थान",
    activeEmergencyBanner: "1 सक्रिय आपातकाल प्रगति में है",
    tapToViewEscalation: "लाइव 4-स्तरीय एस्केलेशन देखने के लिए टैप करें →",
    verified: "सत्यापित",
    emergencyDispatchCenter: "आपातकालीन प्रेषण केंद्र",
    broadcastDesc: "आपातकालीन बटन दबाने से प्रेषण विवरण और स्थान साझा होता है।",
    dispatchDetails: "आपातकालीन प्रेषण विवरण",
    specifyLocationReason: "प्रसारण से पहले स्थान और कारण निर्दिष्ट करें",
    flatUnitLocation: "फ्लैट / इकाई आपातकालीन स्थान",
    reasonForSOS: "आपातकालीन एसओएस का कारण",
    additionalDetails: "अतिरिक्त विवरण (वैकल्पिक)",
    broadcastSOSNow: "अब एसओएस प्रसारित करें",
    fallInjury: "गिरावट / चोट",
    fireSmoke: "आग / धुआं",
    intruderSecurity: "घुसपैठिया / सुरक्षा",
    adminDashboard: "व्यवस्थापक डैशबोर्ड",
    manageSocieties: "सोसायटी प्रबंधन",
    manageResidents: "निवासी प्रबंधन",
    guardsPortal: "सुरक्षा गार्ड पोर्टल",
    volunteersPortal: "स्वयंसेवक पोर्टल",
    availability: "उपलब्धता",
    overviewStats: "अवलोकन आंकड़े",
    activeIncidents: "सक्रिय घटनाएं",
    resolvedIncidents: "हल की गई घटनाएं",
    totalResidents: "कुल निवासी",
    totalSocieties: "कुल सोसायटी",
    addSociety: "सोसायटी जोड़ें",
    addResident: "निवासी जोड़ें",
    incidentHistory: "घटना लेखापरीक्षा लॉग",
    personalDetails: "व्यक्तिगत विवरण",
    societyResidenceMapping: "सोसायटी निवास मैपिंग",
    activeRole: "सक्रिय भूमिका",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    phoneNumber: "फोन नंबर",
    save: "सहेजें",
    edit: "संपादित करें",
    cancel: "रद्द करें",
    addContact: "आपातकालीन संपर्क जोड़ें",
    relationship: "संबंध",
    priority: "प्राथमिकता",
    unverified: "असत्यापित",
    viewMode: "दृश्य मोड:",
    resident: "निवासी",
    security: "सुरक्षा गार्ड",
    volunteer: "स्वयंसेवक",
    admin: "एडमिन",
    sosPanic: "एसओएस आपातकाल",
    activeEmergency: "सक्रिय आपातकाल",
    activeFeedTitle: "सक्रिय आपातकालीन लॉग",
    noActiveAlerts: "कोई सक्रिय आपातकालीन अलर्ट नहीं",
    safeCommunityMsg: "आपका समुदाय वर्तमान में सुरक्षित है।",
    signOut: "साइन आउट करें",
  },
  ta: {
    appTitle: "EmergX",
    appName: "EmergX",
    sosPanicButton: "SOS",
    pressPanic: "அவசர பொத்தானை அழுத்தவும்",
    instantBroadcast: "உடனடி சமூக அவசரகால ஒளிபரப்பு",
    emergencyCategoryPrompt: "அல்லது குறிப்பிட்ட அவசர வகையைத் தேர்ந்தெடுக்கவும்:",
    medicalEmergency: "மருத்துவ அவசரநிலை",
    fireHazard: "தீ விபத்து",
    securityThreat: "பாதுகாப்பு அச்சுறுத்தல்",
    naturalDisaster: "இயற்கை பேரழிவு",
    generalSOS: "பொது SOS",
    liveCountdownTitle: "நேரலை கவுண்ட்டவுன் டைமர்",
    secsToNextTier: "அடுத்த நிலைக்கு வினாடிகள்",
    tier1: "பாதுகாப்பு பணியாளர்கள்",
    tier2: "தன்னார்வ பதிலளிப்பாளர்கள்",
    tier3: "முதன்மை தொடர்பு",
    tier4: "இரண்டாம் நிலை தொடர்பு",
    tier1Short: "பாதுகாப்பு",
    tier2Short: "தன்னார்வலர்",
    tier3Short: "முதன்மை",
    tier4Short: "இரண்டாம் நிலை",
    tierLevelHeader: "நிலை",
    ofFour: "/ 4:",
    welcomeBack: "மீண்டும் வருக",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    login: "உள்நுழைக",
    loggingIn: "உள்நுழைகிறது...",
    dontHaveAccount: "கணக்கு இல்லையா?",
    signUp: "பதிவு செய்க",
    oneTapDemo: "ஒரே-தட்டல் டெமோ கணக்குகள்:",
    acceptedByResponder: "பதிலளிப்பாளரால் ஏற்றுக்கொள்ளப்பட்டது",
    emergencyResolved: "அவசரநிலை தீர்க்கப்பட்டது / நிறுத்தப்பட்டது",
    activeEmergencyTitle: "செயலில் உள்ள அவசர எச்சரிக்கை",
    resolveSOS: "SOS ஐ தீர்க்கவும்",
    cancelSOS: "SOS ஐ ரத்துசெய்",
    contactsTitle: "அவசர தொடர்புகள்",
    alertsTitle: "எச்சரிக்கை அறிவிப்புகள்",
    profileTitle: "பயனர் சுயவிவரம்",
    home: "முகப்பு",
    contacts: "தொடர்புகள்",
    alerts: "அறிவிப்புகள்",
    profile: "சுயவிவரம்",
    languageTab: "மொழி",
    languageTitle: "பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்",
    languageSubtitle: "உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்",
    logout: "வெளியேறு",
    unitLocation: "அலகு / பிளாட் இருப்பிடம்",
    activeEmergencyBanner: "1 செயலில் உள்ள அவசரநிலை நடைபெறுகிறது",
    tapToViewEscalation: "நேரலை 4-நிலை அவசர கண்காணிப்பை பார்க்க அழுத்தவும் →",
    verified: "சரிபார்க்கப்பட்டது",
    emergencyDispatchCenter: "அவசரகால சேவை மையம்",
    broadcastDesc: "அவசர பொத்தானை அழுத்தினால் பிளாட் இருப்பிடம் மற்றும் காரணம் ஒளிபரப்பப்படும்.",
    dispatchDetails: "அவசரகால விநியோக விவரங்கள்",
    specifyLocationReason: "ஒளிபரப்புக்கு முன் இருப்பிடம் மற்றும் காரணத்தைக் குறிப்பிடவும்",
    flatUnitLocation: "பிளாட் / அலகு அவசர இருப்பிடம்",
    reasonForSOS: "அவசர உதவிக்கான காரணம்",
    additionalDetails: "கூடுதல் விவரங்கள் (விருப்பமானது)",
    broadcastSOSNow: "இப்போது SOS ஐ ஒளிபரப்பவும்",
    fallInjury: "வீழ்ச்சி / காயம்",
    fireSmoke: "தீ / புகை",
    intruderSecurity: "ஊடுருவல் / பாதுகாப்பு",
    adminDashboard: "நிர்வாகி போர்டல்",
    manageSocieties: "சங்கங்கள் நிர்வாகம்",
    manageResidents: "குடியிருப்பாளர்கள் நிர்வாகம்",
    guardsPortal: "பாதுகாப்பு காவலர் போர்டல்",
    volunteersPortal: "தன்னார்வலர் போர்டல்",
    availability: "கிடைக்கும்தன்மை",
    overviewStats: "மேலோட்டமான புள்ளிவிவரங்கள்",
    activeIncidents: "செயலில் உள்ள நிகழ்வுகள்",
    resolvedIncidents: "தீர்க்கப்பட்ட நிகழ்வுகள்",
    totalResidents: "மொத்த குடியிருப்பாளர்கள்",
    totalSocieties: "மொத்த சங்கங்கள்",
    addSociety: "சங்கம் சேர்க்க",
    addResident: "குடியிருப்பாளர் சேர்க்க",
    incidentHistory: "நிகழ்வு தணிக்கை பதிவு",
    personalDetails: "தனிப்பட்ட விவரங்கள்",
    societyResidenceMapping: "குடியிருப்பு மேப்பிங்",
    activeRole: "செயலில் உள்ள பங்கு",
    firstName: "முதல் பெயர்",
    lastName: "கடைசி பெயர்",
    phoneNumber: "தொலைபேசி எண்",
    save: "சேமிக்க",
    edit: "திருத்து",
    cancel: "ரத்து செய்",
    addContact: "அவசர தொடர்பு சேர்க்க",
    relationship: "உறவு",
    priority: "முன்னுரிமை",
    unverified: "சரிபார்க்கப்படவில்லை",
    viewMode: "பார்வை முறை:",
    resident: "குடியிருப்பாளர்",
    security: "பாதுகாப்பு காவலர்",
    volunteer: "தன்னார்வலர்",
    admin: "நிர்வாகி",
    sosPanic: "SOS அவசரம்",
    activeEmergency: "செயலில் உள்ள அவசரநிலை",
    activeFeedTitle: "செயலில் உள்ள அவசர பதிவுகள்",
    noActiveAlerts: "செயலில் உள்ள அவசர எச்சரிக்கைகள் இல்லை",
    safeCommunityMsg: "உங்கள் சமூகம் தற்போது பாதுகாப்பாக உள்ளது.",
    signOut: "வெளியேறு",
  },
  te: {
    appTitle: "EmergX",
    appName: "EmergX",
    sosPanicButton: "SOS",
    pressPanic: "అత్యవసర బటన్ నొక్కండి",
    instantBroadcast: "తక్షణ అత్యవసర ప్రసారం",
    emergencyCategoryPrompt: "లేదా నిర్దిష్ట వర్గాన్ని ఎంచుకోండి:",
    medicalEmergency: "వైద్య అత్యవసర పరిస్థితి",
    fireHazard: "అగ్ని ప్రమాదం",
    securityThreat: "రక్షణ ముప్పు",
    naturalDisaster: "ప్రాకృతిక విపత్తు",
    generalSOS: "సాధారణ SOS",
    liveCountdownTitle: "లైవ్ ఎస్కలేషన్ కౌంట్‌డౌన్ టైమర్",
    secsToNextTier: "తదుపరి స్థాయికి సెకన్లు",
    tier1: "సెక్యూరిటీ సిబ్బంది",
    tier2: "వాలంటీర్ రెస్పాండర్లు",
    tier3: "ప్రాథమిక పరిచయం",
    tier4: "ద్వితీయ పరిచయం",
    tier1Short: "సెక్యూరిటీ",
    tier2Short: "వాలంటీర్",
    tier3Short: "ప్రాథమిక",
    tier4Short: "ద్వితీయ",
    tierLevelHeader: "స్థాయి",
    ofFour: "లో 4:",
    welcomeBack: "స్వాగతం",
    emailAddress: "ఈమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    login: "లాగిన్ చేయండి",
    loggingIn: "లాగిన్ అవుతోంది...",
    dontHaveAccount: "ఖాతా లేదా?",
    signUp: "సైన్ అప్ చేయండి",
    oneTapDemo: "ఒకే నొక్కు డెమో ఖాతాలు:",
    acceptedByResponder: "రెస్పాండర్ అంగీకరించారు",
    emergencyResolved: "అత్యవసర పరిష్కరించబడింది",
    activeEmergencyTitle: "సక్రియ అత్యవసర హెచ్చరిక",
    resolveSOS: "SOS పరిష్కరించు",
    cancelSOS: "SOS రద్దు చేయి",
    contactsTitle: "అత్యవసర పరిచయాలు",
    alertsTitle: "హెచ్చరిక ప్రకటనలు",
    profileTitle: "వినియోగదారు ప్రొఫైల్",
    home: "హోమ్",
    contacts: "పరిచయాలు",
    alerts: "హెచ్చరికలు",
    profile: "ప్రొఫైల్",
    languageTab: "భాష",
    languageTitle: "యాప్ భాషను ఎంచుకోండి",
    languageSubtitle: "మీకు ఇష్టమైన భాషను ఎంచుకోండి",
    logout: "లాగ్ అవుట్",
    unitLocation: "ఫ్లాట్ స్థానం",
    activeEmergencyBanner: "1 సక్రియ అత్యవసరం జరుగుతోంది",
    tapToViewEscalation: "లైవ్ ఎస్కలేషన్ చూడటానికి నొక్కండి →",
    verified: "నిరూపించబడింది",
    emergencyDispatchCenter: "అత్యవసర డిస్పాచ్ సెంటర్",
    broadcastDesc: "బటన్ నొక్కడం ద్వారా స్థానం మరియు వివరాలు ప్రసారం చేయబడతాయి.",
    dispatchDetails: "అత్యవసర వివరాలు",
    specifyLocationReason: "ప్రసారానికి ముందు స్థానాన్ని స్పష్టం చేయండి",
    flatUnitLocation: "అత్యవసర స్థానం",
    reasonForSOS: "SOS కారణం",
    additionalDetails: "అదనపు వివరాలు",
    broadcastSOSNow: "ఇప్పుడు ప్రసారం చేయండి",
    fallInjury: "గాయం / పడిపోవడం",
    fireSmoke: "మంటలు / పొగ",
    intruderSecurity: "రక్షణ బెదిరింపు",
    adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    manageSocieties: "సొసైటీ నిర్వహణ",
    manageResidents: "నివాసితుల నిర్వహణ",
    guardsPortal: "గార్డు పోర్టల్",
    volunteersPortal: "వాలంటీర్ పోర్టల్",
    availability: "లభ్యత",
    overviewStats: "గణాంకాలు",
    activeIncidents: "సక్రియ సంఘటనలు",
    resolvedIncidents: "పరిష్కృత సంఘటనలు",
    totalResidents: "మొత్తం నివాసితులు",
    totalSocieties: "మొత్తం సొసైటీలు",
    addSociety: "సొసైటీ జత చేయండి",
    addResident: "నివాసిని జత చేయండి",
    incidentHistory: "సంఘటన లాగ్",
    personalDetails: "వ్యక్తిగత వివరాలు",
    societyResidenceMapping: "నివాస మ్యాపింగ్",
    activeRole: "సక్రియ పాత్ర",
    firstName: "మొదటి పేరు",
    lastName: "చివరి పేరు",
    phoneNumber: "ఫోన్ నంబర్",
    save: "సేవ్ చేయి",
    edit: "సవరించు",
    cancel: "రద్దు చేయి",
    addContact: "పరిచయాన్ని జత చేయండి",
    relationship: "సంబంధం",
    priority: "ప్రాధాన్యత",
    unverified: "పరిశీలించబడలేదు",
    viewMode: "వీక్షణ మోడ్:",
    resident: "నివాసి",
    security: "సెక్యూరిటీ గార్డ్",
    volunteer: "వాలంటీర్",
    admin: "అడ్మిన్",
    sosPanic: "SOS అత్యవసరం",
    activeEmergency: "సక్రియ అత్యవసరం",
    activeFeedTitle: "సక్రియ లాగ్‌లు",
    noActiveAlerts: "సక్రియ హెచ్చరికలు లేవు",
    safeCommunityMsg: "మీ కమ్యూనిటీ సురక్షితంగా ఉంది.",
    signOut: "సైన్ అవుట్",
  },
  bn: {
    appTitle: "EmergX",
    appName: "EmergX",
    sosPanicButton: "SOS",
    pressPanic: "জরুরি বোতাম চাপুন",
    instantBroadcast: "তাত্ক্ষণিক জরুরি সম্প্রচার",
    emergencyCategoryPrompt: "অথবা নির্দিষ্ট বিভাগ বেছে নিন:",
    medicalEmergency: "চিকিৎসা জরুরি অবস্থা",
    fireHazard: "অগ্নি দুর্ঘটনা",
    securityThreat: "নিরাপত্তা ঝুঁকি",
    naturalDisaster: "প্রাকৃতিক দুর্যোগ",
    generalSOS: "সাধারণ SOS",
    liveCountdownTitle: "লাইভ কাউন্টডাউন টাইমার",
    secsToNextTier: "পরবর্তী স্তরের সেকেন্ড",
    tier1: "নিরাপত্তা কর্মী",
    tier2: "স্বেচ্ছাসেবক",
    tier3: "প্রাথমিক যোগাযোগ",
    tier4: "দ্বিতীয় যোগাযোগ",
    tier1Short: "নিরাপত্তা",
    tier2Short: "স্বেচ্ছাসেবক",
    tier3Short: "প্রাথমিক",
    tier4Short: "দ্বিতীয়",
    tierLevelHeader: "স্তর",
    ofFour: "/ ৪:",
    welcomeBack: "স্বাগতম",
    emailAddress: "ইমেল ঠিকানা",
    password: "পাসওয়ার্ড",
    login: "লগ ইন করুন",
    loggingIn: "লগ ইন হচ্ছে...",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    signUp: "সাইন আপ করুন",
    oneTapDemo: "ওয়ান-ট্যাপ ডেমো অ্যাকাউন্ট:",
    acceptedByResponder: "গৃহীত হয়েছে",
    emergencyResolved: "জরুরি অবস্থা সমাধান হয়েছে",
    activeEmergencyTitle: "সক্রিয় জরুরি সতর্কতা",
    resolveSOS: "SOS সমাধান করুন",
    cancelSOS: "SOS বাতিল করুন",
    contactsTitle: "জরুরি যোগাযোগ",
    alertsTitle: "সতর্কতা বিজ্ঞপ্তি",
    profileTitle: "ব্যবহারকারীর প্রোফাইল",
    home: "হোম",
    contacts: "যোগাযোগ",
    alerts: "বিজ্ঞপ্তি",
    profile: "প্রোফাইল",
    languageTab: "ভাষা",
    languageTitle: "অ্যাপের ভাষা নির্বাচন করুন",
    languageSubtitle: "আপনার পছন্দের ভাষা বেছে নিন",
    logout: "লগ আউট",
    unitLocation: "ফ্ল্যাটের অবস্থান",
    activeEmergencyBanner: "১টি সক্রিয় জরুরি অবস্থা চলছে",
    tapToViewEscalation: "লাইভ ট্র্যাকিং দেখতে ট্যাপ করুন →",
    verified: "যাচাইকৃত",
    emergencyDispatchCenter: "জরুরি কেন্দ্র",
    broadcastDesc: "জরুরি বোতাম চাপলে বিবরণ সম্প্রচার করা হবে।",
    dispatchDetails: "জরুরি বিবরণ",
    specifyLocationReason: "সম্প্রচারের আগে অবস্থান নির্দিষ্ট করুন",
    flatUnitLocation: "জরুরি অবস্থান",
    reasonForSOS: "SOS এর কারণ",
    additionalDetails: "অতিরিক্ত তথ্য",
    broadcastSOSNow: "এখন সম্প্রচার করুন",
    fallInjury: "আঘাত / পতন",
    fireSmoke: "আগুন / ধোঁয়া",
    intruderSecurity: "নিরাপত্তা হুমকি",
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    manageSocieties: "সোসাইটি পরিচালনা",
    manageResidents: "বাসিন্দা পরিচালনা",
    guardsPortal: "গার্ড পোর্টাল",
    volunteersPortal: "স্বেচ্ছাসেবক পোর্টাল",
    availability: "উপলব্ধতা",
    overviewStats: "পরিসংখ্যান",
    activeIncidents: "সক্রিয় ঘটনা",
    resolvedIncidents: "সমাধানকৃত ঘটনা",
    totalResidents: "মোট বাসিন্দা",
    totalSocieties: "মোট সোসাইটি",
    addSociety: "সোসাইটি যোগ করুন",
    addResident: "বাসিন্দা যোগ করুন",
    incidentHistory: "ঘটনা লগ",
    personalDetails: "ব্যক্তিগত বিবরণ",
    societyResidenceMapping: "বাসস্থানের তথ্য",
    activeRole: "সক্রিয় ভূমিকা",
    firstName: "প্রথম নাম",
    lastName: "শেষ নাম",
    phoneNumber: "ফোন নম্বর",
    save: "সংরক্ষণ করুন",
    edit: "সম্পাদনা",
    cancel: "বাতিল",
    addContact: "যোগাযোগ যোগ করুন",
    relationship: "সম্পর্ক",
    priority: "অগ্রাধিকার",
    unverified: "অযাচাইকৃত",
    viewMode: "ভিউ মোড:",
    resident: "বাসিন্দা",
    security: "নিরাপত্তা কর্মী",
    volunteer: "স্বেচ্ছাসেবক",
    admin: "অ্যাডমিন",
    sosPanic: "SOS জরুরি",
    activeEmergency: "সক্রিয় জরুরি",
    activeFeedTitle: "সক্রিয় লগ",
    noActiveAlerts: "কোন সক্রিয় সতর্কতা নেই",
    safeCommunityMsg: "আপনার এলাকা এখন নিরাপদ।",
    signOut: "সাইন আউট",
  },
  kn: {
    appTitle: "EmergX",
    appName: "EmergX",
    sosPanicButton: "SOS",
    pressPanic: "ತುರ್ತು ಬಟನ್ ಒತ್ತಿ",
    instantBroadcast: "ತಕ್ಷಣದ ತುರ್ತು ಪ್ರಸಾರ",
    emergencyCategoryPrompt: "ಅಥವಾ ನಿರ್ದಿಷ್ಟ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
    medicalEmergency: "ವೈದ್ಯಕೀಯ ತುರ್ತು",
    fireHazard: "ಅಗ್ನಿ ಅವಘಡ",
    securityThreat: "ಸುರಕ್ಷತಾ ಬೆದರಿಕೆ",
    naturalDisaster: "ನೈಸರ್ಗಿಕ ವಿಕೋಪ",
    generalSOS: "ಸಾಮಾನ್ಯ SOS",
    liveCountdownTitle: "ಲೈವ್ ಎಸ್ಕಲೇಶನ್ ಟೈಮರ್",
    secsToNextTier: "ಮುಂದಿನ ಹಂತಕ್ಕೆ ಸೆಕೆಂಡುಗಳು",
    tier1: "ಸುರಕ್ಷತಾ ಸಿಬ್ಬಂದಿ",
    tier2: "ಸ್ವಯಂಸೇವಕರು",
    tier3: "ಪ್ರಾಥಮಿಕ ಸಂಪರ್ಕ",
    tier4: "ದ್ವಿತೀಯ ಸಂಪರ್ಕ",
    tier1Short: "ಸುರಕ್ಷತೆ",
    tier2Short: "ಸ್ವಯಂಸೇವಕ",
    tier3Short: "ಪ್ರಾಥಮಿಕ",
    tier4Short: "ದ್ವಿತೀಯ",
    tierLevelHeader: "ಹಂತ",
    ofFour: "ರ 4:",
    welcomeBack: "ಸ್ವಾಗತ",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    login: "ಲಾಗಿನ್ ಮಾಡಿ",
    loggingIn: "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
    dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    signUp: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    oneTapDemo: "ಒನ್-ಟ್ಯಾಪ್ ಡೆಮೊ ಖಾತೆಗಳು:",
    acceptedByResponder: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    emergencyResolved: "ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಪರಿಹರಿಸಲಾಗಿದೆ",
    activeEmergencyTitle: "ಸಕ್ರಿಯ ತುರ್ತು ಎಚ್ಚರಿಕೆ",
    resolveSOS: "SOS ಪರಿಹರಿಸಿ",
    cancelSOS: "SOS ರದ್ದುಗೊಳಿಸಿ",
    contactsTitle: "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
    alertsTitle: "ಎಚ್ಚರಿಕೆ ಸೂಚನೆಗಳು",
    profileTitle: "ಬಳಕೆದಾರ ಪ್ರೊಫೈಲ್",
    home: "ಮುಖಪುಟ",
    contacts: "ಸಂಪರ್ಕಗಳು",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    languageTab: "ಭಾಷೆ",
    languageTitle: "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    languageSubtitle: "ನಿಮ್ಮ ಆಯ್ಕೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    unitLocation: "ಫ್ಲಾಟ್ ಸ್ಥಳ",
    activeEmergencyBanner: "1 ಸಕ್ರಿಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ ನಡೆಯುತ್ತಿದೆ",
    tapToViewEscalation: "ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್ ನೋಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ →",
    verified: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    emergencyDispatchCenter: "ತುರ್ತು ಕೇಂದ್ರ",
    broadcastDesc: "ಬಟನ್ ಒತ್ತಿದರೆ ಸ್ಥಳ ಮತ್ತು ವಿವರಗಳನ್ನು ಪ್ರಸಾರ ಮಾಡಲಾಗುತ್ತದೆ.",
    dispatchDetails: "ತುರ್ತು ವಿವರಗಳು",
    specifyLocationReason: "ಪ್ರಸಾರ ಮಾಡುವ ಮೊದಲು ಸ್ಥಳ ಸೂಚಿಸಿ",
    flatUnitLocation: "ತುರ್ತು ಸ್ಥಳ",
    reasonForSOS: "SOS ಕಾರಣ",
    additionalDetails: "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
    broadcastSOSNow: "ಈಗ ಪ್ರಸಾರ ಮಾಡಿ",
    fallInjury: "ಗಾಯ / ಬೀಳುವುದು",
    fireSmoke: "ಬೆಂಕಿ / ಹೊಗೆ",
    intruderSecurity: "ಸುರಕ್ಷತಾ ತೊಂದರೆ",
    adminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    manageSocieties: "ಸೊಸೈಟಿ ನಿರ್ವಹಣೆ",
    manageResidents: "ನಿವಾಸಿಗಳ ನಿರ್ವಹಣೆ",
    guardsPortal: "ಗಾರ್ಡ್ ಪೋರ್ಟಲ್",
    volunteersPortal: "ಸ್ವಯಂಸೇವಕ ಪೋರ್ಟಲ್",
    availability: "ಲಭ್ಯತೆ",
    overviewStats: "ಅಂಕಿಅಂಶಗಳು",
    activeIncidents: "ಸಕ್ರಿಯ ಘಟನೆಗಳು",
    resolvedIncidents: "ಪರಿಹರಿಸಿದ ಘಟನೆಗಳು",
    totalResidents: "ಒಟ್ಟು ನಿವಾಸಿಗಳು",
    totalSocieties: "ಒಟ್ಟು ಸೊಸೈಟಿಗಳು",
    addSociety: "ಸೊಸೈಟಿ ಸೇರಿಸಿ",
    addResident: "ನಿವಾಸಿ ಸೇರಿಸಿ",
    incidentHistory: "ಘಟನೆಗಳ ದಾಖಲೆ",
    personalDetails: "ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
    societyResidenceMapping: "ನಿವಾಸ ವಿವರಗಳು",
    activeRole: "ಸಕ್ರಿಯ ಪಾತ್ರ",
    firstName: "ಮೊದಲ ಹೆಸರು",
    lastName: "ಕೊನೆಯ ಹೆಸರು",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    save: "ಉಳಿಸಿ",
    edit: "ಸಂಪಾದಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    addContact: "ಸಂಪರ್ಕ ಸೇರಿಸಿ",
    relationship: "ಸಂಬಂಧ",
    priority: "ಆದ್ಯತೆ",
    unverified: "ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ",
    viewMode: "ವೀಕ್ಷಣೆ ಮೋಡ್:",
    resident: "ನಿವಾಸಿ",
    security: "ಸುರಕ್ಷತಾ ಸಿಬ್ಬಂದಿ",
    volunteer: "ಸ್ವಯಂಸೇವಕ",
    admin: "ಅಡ್ಮಿನ್",
    sosPanic: "SOS ತುರ್ತು",
    activeEmergency: "ಸಕ್ರಿಯ ತುರ್ತು",
    activeFeedTitle: "ಸಕ್ರಿಯ ದಾಖಲೆಗಳು",
    noActiveAlerts: "ಯಾವುದೇ ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ",
    safeCommunityMsg: "ನಿಮ್ಮ ಸಮುದಾಯ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
    signOut: "ಸೈನ್ ಔಟ್",
  },
};

const STORAGE_KEY_LANG = 'app_user_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY_LANG).then((saved) => {
      if (saved && (saved === 'en' || saved === 'hi' || saved === 'ta' || saved === 'te' || saved === 'bn' || saved === 'kn')) {
        setLanguageState(saved as Language);
      }
    });
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem(STORAGE_KEY_LANG, lang);
  };

  const t = (key: string): string => {
    const langDict = translations[language] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
